name: Lint

inputs:
  SAVE_REPORTS:
    description: 'Upload reports for sonar'
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        check-latest: true
        go-version-file: ./go.mod

    - name: Download .golangci.yml
      shell: bash
      run: curl https://raw.githubusercontent.com/Projects-for-Fun/golangci/main/.golangci.yml --output /tmp/.golangci.yml

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: -v -c /tmp/.golangci.yml

        # show only new issues if it's a pull request
        # only-new-issues: true

        # all caching functionality will be complete disabled, takes precedence over all other caching options
        # skip-cache: true

        # don't cache or restore ~/go/pkg.
        # skip-pkg-cache: true

        # don't cache or restore ~/.cache/go-build.
        # skip-build-cache: true

        # TODO export report to sonar