name: Unit tests

inputs:
  SAVE_REPORTS:
    description: 'Upload reports for sonar'
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        check-latest: true
        go-version-file: ./go.mod

    - name: Verify dependencies
      shell: bash
      run: go mod verify

    - run: mkdir -p ./files
      shell: bash

    - name: Unit tests & generate coverage and report
      shell: bash
      run: |
        go test "./..." -coverprofile="./files/coverage.out" -covermode=count -json > ./files/report.json

    - name: Upload coverage.out? => ${{ inputs.SAVE_REPORTS }}
      uses: actions/upload-artifact@v3
      if: ${{ inputs.SAVE_REPORTS }}
      with:
        name: coverage.out
        path: ./files/coverage.out
        if-no-files-found: warn

    - name: Upload report.json? => ${{ inputs.SAVE_REPORTS }}
      uses: actions/upload-artifact@v3
      if: ${{ inputs.SAVE_REPORTS }}
      with:
        name: report.json
        path: ./files/report.json
        if-no-files-found: warn

#    - name: Display structure of files
#      shell: bash
#      run: ls -R