version: "3.9"
services:
  neo4j:
    image: neo4j:4.4.22
    environment:
      - NEO4J_AUTH=neo4j/11223344
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "neo4j://neo4j:11223344@neo4j:7687", "up"]
    restart: on-failure
    depends_on:
      - neo4j