version: "3.9"
services:
  neo4j:
    image: neo4j:4.4.22
    environment:
      - NEO4J_AUTH=neo4j/11223344
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "neo4j://neo4j:11223344@neo4j:7687", "up"]
    restart: on-failure
    depends_on:
      - neo4j
  #    depends_on:
  #      neo4j:
  #        condition: service_healthy

  webservice:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    env_file: .env.local
    environment:
      - SERVICE_PORT=3000
      - DB_URI=neo4j://neo4j:11223344@neo4j:7687

  integration_tests:
    image: golang:1.20.5-alpine
    entrypoint: ["sh"]
    volumes:
      - .:/app
    command: ["-c", "cd /app/test/integrationtests && go test -v ./..."]
    env_file: .env.local
    environment:
      - RUN_INTEGRATION_TESTS=1
      - SERVICE_PORT=3000
      - DB_URI=neo4j://neo4j:11223344@neo4j:7687