name: Integration tests Test

on:
  push

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build infra
        run: docker-compose -f docker-compose.integration-pipeline.yml up -d neo4j && \
          docker-compose -f docker-compose.integration-pipeline.yml up -d migrate

      - name: Run integration tests
        run: docker-compose -f docker-compose.integration-pipeline.yml up integration_tests --build --abort-on-container-exit --exit-code-from=integration_tests --force-recreate

      - name: Cleanup
        run: docker-compose -f docker-compose.integration-pipeline.yml down --remove-orphans