name: Integration tests Test

on:
  commit

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:4.4.22
        environment:
          NEO4J_AUTH: neo4j/11223344
        ports:
          - 7474:7474
          - 7687:7687
