name: Integration tests Test

on:
  push

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build infra - neo4j
        run: docker-compose -f docker-compose.integration-pipeline.yml up -d neo4j

      - name: Build infra - migrate
        run: docker-compose -f docker-compose.integration-pipeline.yml up -d migrate

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version-file: ./go.mod

      - name: Set env vars for integration tests
        run: |
          echo "RUN_INTEGRATION_TESTS=1" >> "$GITHUB_ENV" && \
          echo "ENVIRONMENT=it-pipeline" >> "$GITHUB_ENV" && \
          echo "SERVICE_NAME=thefoodbook" >> "$GITHUB_ENV" && \
          echo "SERVICE_PORT=3000" >> "$GITHUB_ENV" && \
          echo "LOG_LEVEL=info" >> "$GITHUB_ENV" && \
          echo "LOG_FORMAT=console" >> "$GITHUB_ENV" && \
          echo "DB_URI=neo4j://neo4j:11223344@localhost:7687" >> "$GITHUB_ENV" && \
          echo "DB_USER=neo4j" >> "$GITHUB_ENV" && \
          echo "DB_PASS=11223344" >> "$GITHUB_ENV" && \
          echo "JWT_KEY=my_random_secret_key_for_testing" >> "$GITHUB_ENV"

      - name: Run integration tests
        run: cd ./test/integrationtests && go test -v ./...

#      - name: Run integration tests
#        run: docker-compose -f docker-compose.integration-pipeline.yml up integration_tests

      - name: Cleanup
        run: docker-compose -f docker-compose.integration-pipeline.yml down --remove-orphans