name: Integration tests Test

on:
  push

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build infra - neo4j
        run: docker-compose -f docker-compose.integration-pipeline.yml up -d neo4j

      - name: Build infra - migrate
        run: docker-compose -f docker-compose.integration-pipeline.yml up -d migrate

      - name: Run integration tests
        run: docker-compose -f docker-compose.integration-pipeline.yml up integration_tests --abort-on-container-exit --exit-code-from=integration_tests --force-recreate

      - name: Cleanup
        run: docker-compose -f docker-compose.integration-pipeline.yml down --remove-orphans